### ISSUE TITLE
Does this support Vulkan/OpenGl?

### ISSUE THREAD

**Issue by amlan111** [timminator/Enhanced-GPU-PV#4]
Idk if it's the right place to ask but I read somewhere that vulkan/OpenGL not working was a limitation of parsec. So if I use the virtual display driver with sunshine, will Vulkan/OpenGL work?

**Comment by h4n1virus** [comment]
OpenGL seems to work fine with parsec, haven't tested Vulkan yet.

**Comment by amlan111** [comment]
> OpenGL seems to work fine with parsec, haven't tested Vulkan yet.

OpenGL works for me too (tested with rocket leauge) but vulkan only works if hyperV display adapter is on, but having it on severely reduces the overall performance of the VM.

**Comment by timminator** [comment]
Are you running an Nvidia or AMD graphics card? Im quite curious.
I talked about OpenGL/Vulkan support in this [thread](https://github.com/timminator/Enhanced-GPU-PV/issues/2) and this [thread](https://github.com/jamesstringerparsec/Easy-GPU-PV/issues/342).
Using the Virtual Display Driver and Sunshine should not change anything about the OpenGl/Vulkan support. It is not per se a limitation of parsec, it is a limitation of the Virtual Display and here the situation is exactly the same for both solutions.
In the first thread I mentioned it looks like AMD users can enjoy full OpenGL/Vulkan support out of the box whereas Nvidia users can enable OpenGL and limited Vulkan support by reenabling the HyperV display in the Display settings.
What did you use to test vulkan support after enabling the hyperV display, if I may ask?

**Comment by amlan111** [comment]
> Are you running an Nvidia or AMD graphics card? Im quite curious. I talked about OpenGL/Vulkan support in this [thread](https://github.com/timminator/Enhanced-GPU-PV/issues/2) and this [thread](https://github.com/jamesstringerparsec/Easy-GPU-PV/issues/342). Using the Virtual Display Driver and Sunshine should not change anything about the OpenGl/Vulkan support. It is not per se a limitation of parsec, it is a limitation of the Virtual Display and here the situation is exactly the same for both solutions. In the first thread I mentioned it looks like AMD users can enjoy full OpenGL/Vulkan support out of the box whereas Nvidia users can enable OpenGL and limited Vulkan support by reenabling the HyperV display in the Display settings. What did you use to test vulkan support after enabling the hyperV display, if I may ask?

I have a Nvidia GeForce 4060 unfortunately, I use botw on yuzu to test vulkan. Rhe game won't even if I don't have hyperV adapter on, yuzu has a openGL mode too but that doesn't work without hyperV adapter either. If I have the adapter on then  both OpenGL and Vulkan works but everything is laggy. Including games that previously ran smooth with hyperV adapter disabled, like rocket leauge, which google says uses OpenGL.
